// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoq-Xl5bNPCjMX3UzzXWwjRYbxSgKA8Os',
    appId: '1:796195446728:web:07bf2686c4cdd6fa0eeafd',
    messagingSenderId: '796195446728',
    projectId: 'app-filmes-mobile',
    authDomain: 'app-filmes-mobile.firebaseapp.com',
    storageBucket: 'app-filmes-mobile.appspot.com',
    measurementId: 'G-8PHM1050DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7tIMJYarLXdM7pWmrR0UebjkPQffqCQ',
    appId: '1:796195446728:android:07cb499e71a58f640eeafd',
    messagingSenderId: '796195446728',
    projectId: 'app-filmes-mobile',
    storageBucket: 'app-filmes-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmyY3eNprkXDppSe1O5PhFUSym1pcs440',
    appId: '1:796195446728:ios:c48172d56b97843c0eeafd',
    messagingSenderId: '796195446728',
    projectId: 'app-filmes-mobile',
    storageBucket: 'app-filmes-mobile.appspot.com',
    iosClientId: '796195446728-i42fnfuc4oirq00i4gr34b6i1q7fcr2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFilmes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmyY3eNprkXDppSe1O5PhFUSym1pcs440',
    appId: '1:796195446728:ios:c48172d56b97843c0eeafd',
    messagingSenderId: '796195446728',
    projectId: 'app-filmes-mobile',
    storageBucket: 'app-filmes-mobile.appspot.com',
    iosClientId: '796195446728-i42fnfuc4oirq00i4gr34b6i1q7fcr2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFilmes',
  );
}
